import type { Project, Task, Document as Doc, GA4Metrics, GSCMetrics } from "@/types";

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Tpaga Studio",
    domain: "tpaga-studio.lovable.app",
    ga4_property_id: "123456789",
    gsc_site_url: "https://tpaga-studio.lovable.app",
    ga4_credentials: null,
    gsc_credentials: null,
    status: "active",
    start_date: "2026-01-15",
    client_id: "c1",
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-05-01T00:00:00Z",
    client: {
      id: "c1",
      full_name: "Carlos Martínez",
      role: "client",
      avatar_url: null,
      created_at: "2026-01-15T00:00:00Z",
    },
  },
  {
    id: "2",
    name: "Dental Pro",
    domain: "dentalpro.com",
    ga4_property_id: null,
    gsc_site_url: null,
    ga4_credentials: null,
    gsc_credentials: null,
    status: "active",
    start_date: "2026-03-01",
    client_id: "c2",
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-04-20T00:00:00Z",
    client: {
      id: "c2",
      full_name: "María López",
      role: "client",
      avatar_url: null,
      created_at: "2026-03-01T00:00:00Z",
    },
  },
  {
    id: "3",
    name: "FitLife Gym",
    domain: "fitlifegym.co",
    ga4_property_id: null,
    gsc_site_url: null,
    ga4_credentials: null,
    gsc_credentials: null,
    status: "paused",
    start_date: "2025-11-10",
    client_id: "c3",
    created_at: "2025-11-10T00:00:00Z",
    updated_at: "2026-02-15T00:00:00Z",
    client: {
      id: "c3",
      full_name: "Andrés Gómez",
      role: "client",
      avatar_url: null,
      created_at: "2025-11-10T00:00:00Z",
    },
  },
];

export const mockTasks: Task[] = [
  {
    id: "t1",
    project_id: "1",
    title: "Auditoría técnica completa",
    description: "Revisar velocidad, Core Web Vitals, errores de rastreo",
    category: "tecnico",
    status: "completado",
    priority: "alta",
    assigned_to: null,
    due_date: "2026-02-01",
    visible_to_client: true,
    created_at: "2026-01-20T00:00:00Z",
    updated_at: "2026-01-28T00:00:00Z",
  },
  {
    id: "t2",
    project_id: "1",
    title: "Optimización de meta tags",
    description: "Title tags y meta descriptions para las 20 páginas principales",
    category: "contenido",
    status: "en_progreso",
    priority: "alta",
    assigned_to: null,
    due_date: "2026-05-15",
    visible_to_client: true,
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-05-01T00:00:00Z",
  },
  {
    id: "t3",
    project_id: "1",
    title: "Link building - Mes 1",
    description: "Conseguir 10 backlinks de calidad",
    category: "enlaces",
    status: "pendiente",
    priority: "media",
    assigned_to: null,
    due_date: "2026-06-01",
    visible_to_client: true,
    created_at: "2026-05-01T00:00:00Z",
    updated_at: "2026-05-01T00:00:00Z",
  },
  {
    id: "t4",
    project_id: "1",
    title: "Configurar Google Analytics 4",
    description: "Instalar y verificar GA4 en el sitio",
    category: "analytics",
    status: "completado",
    priority: "alta",
    assigned_to: null,
    due_date: "2026-01-25",
    visible_to_client: true,
    created_at: "2026-01-16T00:00:00Z",
    updated_at: "2026-01-24T00:00:00Z",
  },
  {
    id: "t5",
    project_id: "2",
    title: "Investigación de keywords",
    description: "Keywords para servicios dentales principales",
    category: "contenido",
    status: "en_progreso",
    priority: "alta",
    assigned_to: null,
    due_date: "2026-05-10",
    visible_to_client: true,
    created_at: "2026-03-05T00:00:00Z",
    updated_at: "2026-05-01T00:00:00Z",
  },
  {
    id: "t6",
    project_id: "1",
    title: "Revisión de estructura interna de enlaces",
    description: null,
    category: "tecnico",
    status: "pendiente",
    priority: "baja",
    assigned_to: null,
    due_date: "2026-06-15",
    visible_to_client: false,
    created_at: "2026-05-02T00:00:00Z",
    updated_at: "2026-05-02T00:00:00Z",
  },
];

export const mockDocuments: Doc[] = [
  {
    id: "d1",
    project_id: "1",
    title: "Propuesta SEO - Tpaga Studio",
    type: "propuesta",
    file_url: "#",
    content: null,
    visible_to_client: true,
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "d2",
    project_id: "1",
    title: "Auditoría técnica - Enero 2026",
    type: "auditoria",
    file_url: "#",
    content: null,
    visible_to_client: true,
    created_at: "2026-01-30T00:00:00Z",
  },
  {
    id: "d3",
    project_id: "1",
    title: "Reporte mensual - Abril 2026",
    type: "reporte",
    file_url: "#",
    content: null,
    visible_to_client: true,
    created_at: "2026-05-01T00:00:00Z",
  },
];

function generateDateSeries(days: number) {
  const data = [];
  const now = new Date();
  for (let i = days; i >= 0; i--) {
    const d = new Date(now);
    d.setDate(d.getDate() - i);
    data.push(d.toISOString().split("T")[0]);
  }
  return data;
}

export const mockGA4: GA4Metrics = {
  sessions: 4832,
  totalUsers: 3241,
  screenPageViews: 12450,
  bounceRate: 42.3,
  sessionsByDate: generateDateSeries(30).map((date) => ({
    date,
    sessions: Math.floor(100 + Math.random() * 120),
  })),
  topPages: [
    { path: "/", views: 3200 },
    { path: "/servicios", views: 1800 },
    { path: "/portafolio", views: 1450 },
    { path: "/contacto", views: 980 },
    { path: "/blog/guia-seo", views: 720 },
    { path: "/nosotros", views: 650 },
    { path: "/blog/tendencias-2026", views: 540 },
    { path: "/precios", views: 480 },
    { path: "/blog/diseno-web", views: 390 },
    { path: "/faq", views: 240 },
  ],
};

export const mockGSC: GSCMetrics = {
  clicks: 2856,
  impressions: 48230,
  ctr: 5.9,
  position: 18.4,
  clicksByDate: generateDateSeries(30).map((date) => ({
    date,
    clicks: Math.floor(60 + Math.random() * 80),
    impressions: Math.floor(1200 + Math.random() * 800),
  })),
  topQueries: [
    { query: "tpaga studio", clicks: 320, impressions: 1200, position: 1.2 },
    { query: "diseño web colombia", clicks: 180, impressions: 4500, position: 8.5 },
    { query: "agencia diseño web", clicks: 145, impressions: 3800, position: 12.3 },
    { query: "portafolio diseño web", clicks: 98, impressions: 2100, position: 15.7 },
    { query: "precios diseño web", clicks: 76, impressions: 1900, position: 19.2 },
    { query: "diseño web profesional", clicks: 65, impressions: 2800, position: 22.1 },
    { query: "crear pagina web", clicks: 54, impressions: 5200, position: 28.4 },
    { query: "desarrollo web medellín", clicks: 48, impressions: 1100, position: 9.8 },
    { query: "studio diseño digital", clicks: 42, impressions: 890, position: 6.3 },
    { query: "web developer colombia", clicks: 38, impressions: 1600, position: 14.9 },
  ],
  topPages: [
    { page: "/", clicks: 890, impressions: 12000 },
    { page: "/servicios", clicks: 540, impressions: 8500 },
    { page: "/portafolio", clicks: 380, impressions: 5200 },
    { page: "/blog/guia-seo", clicks: 290, impressions: 6800 },
    { page: "/contacto", clicks: 210, impressions: 3100 },
  ],
};
